language: node_js
node_js:
  - 11

cache:
  directories:
    - node_modules
    - dist # cache for bundlesize

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
    - stage: bundlesize
      script: npm run bundlesize

stages:
  - test
  - build
  - bundlesize
