language: node_js
node_js:
  - 11

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build

stages:
  - test
  - build
