name: build

on: [push]

env:
  CI: true

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 11.x

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: save bundles
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

      - name: test
        run: npm test

      - name: bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
          CI_REPO_OWNER: mindtraveller
          CI_REPO_NAME: react-password-strometer
          CI_COMMIT_MESSAGE: unknown commit message
          CI_COMMIT_SHA: $GITHUB_SHA
        run: npm run bundlesize
