name: build

on: [push, pull_request]

env:
  CI: true

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 11.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload bundle
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

      - name: Test
        run: npm test

      - name: Bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
          CI_REPO_OWNER: mindtraveller
          CI_REPO_NAME: react-password-strometer
          CI_COMMIT_MESSAGE: unknown commit message
          CI_COMMIT_SHA: $GITHUB_SHA
        run: npm run bundlesize

  job2:
    name: Create Github release
    runs-on: ubuntu-latest
    needs: job1
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 11.x

      - name: Install auto-changelog
        run: npm i auto-changelog

      - name: Generate changelog
        run: auto-changelog --starting-commit $(git rev-list $(git tag --sort=-v:refname | sed -n '2 p').. | tail -1)

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md

  job3:
    name: Publish npm release
    runs-on: ubuntu-latest
    needs: job1
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
          registry-url: 'https://registry.npmjs.org'

      - name: Download bundle
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

