name: prerelease

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  publish_to_npm:
    name: Publish NPM release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish prerelease
        run: npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

