name: pull_request_opened

on:
  pull_request:
    types: [opened]

jobs:
  job1:
    name: Notify owner
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: |
            New pull request: ${{github.event.pull_request.title}}.
            Checkout it out: ${{github.event.pull_request.html_url}}.