name: pull_request_review

on:
    pull_request:
        types: [review_requested]

jobs:
  job1:
    name: Notify
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          format: markdown
          message: |
            Review requested for _${{github.event.pull_request.title}}_.
            Checkout it out [here](${{github.event.pull_request.html_url}}).

