name: pull_request_review

on:
  pull_request:
    types: [review_requested]

jobs:
  job1:
    name: Notify
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: |
            Review requested for `${{github.event.pull_request.title}}`.
            Checkout it out: ${{github.event.pull_request.html_url}}.

